from get_data.data_from_text import (
    get_well_number,
    get_cycle_count,
    get_process_solution,
    get_clay_powder,
    get_buffer,
    get_wood_flour,
    get_primary_solution,
    get_neftenol_and_waste_water,
    get_hes,
    get_squeeze,
    get_injection_pressure,
    get_squeeze_final,
    get_squeeze_in_process,
    get_rbm,
    get_ngdu,
    get_dates,
    get_area
)

COLUMNS_VDS = [
    'Скважина',
    'Площадь',
    'НГДУ',
    'Дата начала ремонта',
    'Дата окончания ремонта',
    'Приемистость скважины на 1-й скорости',
    'Приемистость скважины на 2-й скорости',
    'Приемистость скважины на 3-й скорости',
    'Количество циклов',
    'Объем технонологического раствора',
    'Объем раствора глинопорошка',
    'Концентрация глинопорошка',
    'Масса глинопопрошка',
    'Объем буфера ',
    'Объем раствора древесной муки',
    'Концентрация древесной муки',
    'Масса древесной муки',
    'Объем межцикловой продавки',
    'Давление закачки',
    'Объем финальной продавки',
    'Приемистость скважины на 1-й скорости после закачки',
    'Приемистость скважины на 2-й скорости после закачки',
    'Приемистость скважины на 3-й скорости после закачки',
]
DATA_FIELDS_VDS = [
    'well', 'area', 'ngdu', 'dates', 'cycle_count', 'process_solution',
    'clay_powder', 'buffer', 'wood_flour', 'squeeze',
    'injection_pressure', 'squeeze_final'
]
DATA_GET_FUNCTIONS_VDS = [
    get_well_number,
    get_area,
    get_ngdu,
    get_dates,
    get_cycle_count,
    get_process_solution,
    get_clay_powder,
    get_buffer,
    get_wood_flour,
    get_squeeze,
    get_injection_pressure,
    get_squeeze_final,
]
COLUMNS_VDS_RBM = [
    'Скважина',
    'Площадь',
    'НГДУ',
    'Дата начала ремонта',
    'Дата окончания ремонта',
    'Приемистость скважины на 1-й скорости',
    'Приемистость скважины на 2-й скорости',
    'Приемистость скважины на 3-й скорости',
    'Объем технонологического раствора',
    'Концентрация РБМ 1-ая оторочка',
    'Концентрация РБМ 2-ая оторочка',
    'Концентрация РБМ 3-ая оторочка',
    'Продавка в процессе закачки',
    'Давление закачки',
    'Объем финальной продавки',
    'Приемистость скважины на 1-й скорости после закачки',
    'Приемистость скважины на 2-й скорости после закачки',
    'Приемистость скважины на 3-й скорости после закачки',
]
DATA_FIELDS_VDS_RBM = [
    'well', 'area', 'ngdu', 'dates', 'process_solution', 'rbm', 'squeeze_in_process',
    'injection_pressure', 'squeeze_final'
]
DATA_GET_FUNCTIONS_VDS_RBM = [
    get_well_number,
    get_area,
    get_ngdu,
    get_dates,
    get_process_solution,
    get_rbm,
    get_squeeze_in_process,
    get_injection_pressure,
    get_squeeze_final,
]
COLUMNS_HES = [
    'Скважина',
    'Площадь',
    'НГДУ',
    'Дата начала ремонта',
    'Дата окончания ремонта',
    'Приемистость скважины на 1-й скорости',
    'Приемистость скважины на 2-й скорости',
    'Приемистость скважины на 3-й скорости',
    'Объем первичного раствора',
    'Объем нефтенола в первичном растворе',
    'Объем воды в первичном растворе',
    'Объем ГЭР',
    'Концентрация ПАВ в ГЭР',
    'Давление закачки',
    'Объем продавки',
    'Приемистость скважины на 1-й скорости после закачки',
    'Приемистость скважины на 2-й скорости после закачки',
    'Приемистость скважины на 3-й скорости после закачки',
]
DATA_FIELDS_HES = [
    'well', 'area', 'ngdu', 'dates', 'primary_solution', 'neftenol_waste_water',
    'hes', 'injection_pressure', 'squeeze_final'
]
DATA_GET_FUNCTIONS_HES = [
    get_well_number,
    get_area,
    get_ngdu,
    get_dates,
    get_primary_solution,
    get_neftenol_and_waste_water,
    get_hes,
    get_injection_pressure,
    get_squeeze_final,
]
